const Q=[['goals','今日核心目标','你今天最想推进的 1–3 件事是什么？','目标尽量具体：完成哪一部分、验证什么假设，或做出什么决策。'],['completed','完成的工作','今天实际做了哪些工作？','可记录阅读、实验、写作、代码、讨论等，并写下关键产出。'],['solved','已解决的问题','今天解决了什么问题？','写下解决路径，未来遇到类似问题会很有用。'],['unsolved','未解决的问题','还有哪些问题没有解决？','描述当前状态、已尝试的方法和下一步最小行动。'],['blockers','难点 / 卡点','今天最消耗你的地方是什么？','可以是技术、方法、时间管理或沟通上的阻碍。'],['tomorrow','明日计划','明天最重要的下一步是什么？','给自己留一个可启动的动作，而不是笼统的愿望。']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let records=JSON.parse(localStorage.getItem('phd-review-records')||'[]'),draft={},step=0,coords='';
const day=()=>new Date().toISOString().slice(0,10),fmt=d=>new Date(d+'T12:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'}),save=()=>localStorage.setItem('phd-review-records',JSON.stringify(records)),esc=s=>(s||'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='home')home();if(id==='archive')archive();if(id==='insights')insights()}
function home(){let r=records.find(x=>x.date===day());$('#heroTitle').textContent=r?'今天的复盘已完成':'今天的研究，留下些什么？';$('#heroSub').textContent=r?'随时查看、补充或修改今天的记录。':'用 5–10 分钟，完成一次有条理的复盘。';$('#heroCta').textContent=r?'查看 / 修改今日复盘　›':'开始今日复盘　›';let a=records.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);$('#recent').innerHTML=a.length?a.map(card).join(''):'<p class="empty">还没有记录。第一篇会从今天开始。</p>';bindCards()}
function card(r){return `<button class="record" data-id="${r.id}"><p>${fmt(r.date)}</p><strong>${esc((r.goals||'每日复盘').split('\n')[0])}</strong><small>${esc((r.completed||r.goals||'未填写内容').split('\n')[0])}</small></button>`}function bindCards(){$$('.record').forEach(x=>x.onclick=()=>detail(records.find(r=>r.id===x.dataset.id)))}
function start(){draft={...(records.find(x=>x.date===day())||{id:crypto.randomUUID(),date:day()})};step=0;coords=draft.location||'';locate();page('review');renderQ()}
function renderQ(){let q=Q[step];$('#stepText').textContent=`问题 ${step+1} / ${Q.length}`;$('#bar').style.width=`${(step+1)/Q.length*100}%`;$('#qTitle').textContent=q[1];$('#qText').textContent=q[2];$('#qHint').textContent=q[3];$('#answer').value=draft[q[0]]||'';$('#back').style.visibility=step?'visible':'hidden';$('#next').textContent=step===Q.length-1?'生成今日记录':'下一题'}function persist(){draft[Q[step][0]]=$('#answer').value.trim()}
function advance(){persist();if(step<Q.length-1){step++;renderQ()}else{draft.location=coords;let i=records.findIndex(x=>x.date===draft.date);i<0?records.push(draft):records[i]=draft;save();page('home');detail(draft)}}
function locate(){if(!navigator.geolocation){$('#location').textContent='此浏览器不支持定位';return}$('#location').textContent='正在获取记录位置…';navigator.geolocation.getCurrentPosition(p=>{coords=`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;$('#location').textContent=`已记录位置：${coords}`},e=>$('#location').textContent=e.code===1?'未授予位置权限；仍可正常复盘。':'未能定位，可稍后刷新。',{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
function archive(){let term=$('#search').value.toLowerCase();let a=records.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(x=>JSON.stringify(x).toLowerCase().includes(term));$('#records').innerHTML=a.length?a.map(card).join(''):'<p class="empty">没有找到匹配的记录。</p>';bindCards()}
function detail(r){if(!r)return;let l=r.location?`<div class="detail-item"><h3>记录位置</h3><a target="_blank" href="https://maps.apple.com/?ll=${encodeURIComponent(r.location)}">${r.location}</a></div>`:'';$('#detail').innerHTML=`<h2>${fmt(r.date)} · 每日复盘</h2>${l}${Q.map(q=>`<div class="detail-item"><h3>${q[1]}</h3>${list(r[q[0]])}</div>`).join('')}`;$('#modal').classList.remove('hidden')}
function list(v){let a=(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return a.length?`<ol>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:'<span>—</span>'}
let chartDays=7;function insights(){let cutoff=new Date();cutoff.setDate(cutoff.getDate()-chartDays+1);let a=records.filter(x=>new Date(x.date+'T12:00')>=cutoff);let count=k=>a.filter(x=>x[k]?.trim()).length;$('#stats').innerHTML=`<div><span>记录天数</span><b>${a.length}</b><small>/ ${chartDays} 天</small></div><div><span>解决问题</span><b>${count('solved')}</b><small>次有沉淀</small></div><div><span>待推进</span><b>${count('unsolved')}</b><small>条记录</small></div>`;let b=[];for(let i=chartDays-1;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let r=records.find(x=>x.date===d.toISOString().slice(0,10)),n=r?Q.filter(q=>r[q[0]]?.trim()).length:0;b.push(`<div><i style="height:${n/6*100}%"></i><span>${d.getMonth()+1}/${d.getDate()}</span></div>`)}$('#chart').innerHTML=b.join('');$('#summaryTitle').textContent=chartDays===7?'本周复盘':'本月复盘';$('#summary').textContent=a.length?`你在这段时间完成了 ${a.length} 天记录。优先回看“未解决的问题”，把它们转化为下一次行动。`:'开始每日记录后，这里会自动生成阶段性回顾。'}
function exportExcel(){if(!records.length)return alert('还没有可导出的记录。');if(!window.XLSX)return alert('Excel 组件未加载，请联网后重试。');let rows=records.map(r=>Object.fromEntries([['日期',r.date],['记录位置',r.location||''],...Q.map(q=>[q[1],(r[q[0]]||'').split(/\r?\n/).filter(Boolean).map((x,i)=>`${i+1}. ${x}`).join('\n')])])),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:13},{wch:20},...Q.map(()=>({wch:35}))];let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'每日复盘');let d=new Date(),p=n=>String(n).padStart(2,'0'),stamp=`${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;XLSX.writeFile(wb,`博士日课复盘记录_${stamp}.xlsx`)}
function download(content,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function calendar(){download('BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:phd-review-2300\r\nDTSTART:20260730T230000\r\nDTEND:20260730T231000\r\nRRULE:FREQ=DAILY\r\nSUMMARY:博士日课：每日复盘\r\nDESCRIPTION:花 5–10 分钟记录今天的工作、问题和明日计划。\r\nBEGIN:VALARM\r\nTRIGGER:PT0M\r\nACTION:DISPLAY\r\nDESCRIPTION:每日复盘时间到了\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR','博士日课-每晚23点提醒.ics','text/calendar')}
$('#today').textContent=fmt(day());$('#start').onclick=start;$('#next').onclick=advance;$('#back').onclick=()=>{persist();if(step){step--;renderQ()}};$('#refreshLocation').onclick=locate;$('#settings').onclick=()=>page('preferences');$$('nav button').forEach(x=>x.onclick=()=>page(x.dataset.page));$('#search').oninput=archive;$$('.segmented button').forEach(x=>x.onclick=()=>{chartDays=+x.dataset.days;$$('.segmented button').forEach(y=>y.classList.toggle('selected',y===x));insights()});$('#excel').onclick=exportExcel;$('#json').onclick=()=>download(JSON.stringify(records,null,2),'博士日课数据备份.json','application/json');$('#calendar').onclick=calendar;$('#locate').onclick=locate;$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};home();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
