const Q=[['completed','完成的工作','今天实际做了哪些工作？','可记录阅读、实验、写作、代码、讨论等，并写下关键产出。'],['solved','已解决的问题','今天解决了什么问题？','写下解决路径，未来遇到类似问题会很有用。'],['unsolved','未解决的问题','还有哪些问题没有解决？','描述当前状态、已尝试的方法和下一步最小行动。'],['blockers','难点 / 卡点','今天最消耗你的地方是什么？','可以是技术、方法、时间管理或沟通上的阻碍。'],['tomorrow','明日计划','明天最重要的下一步是什么？','给自己留一个可启动的动作，而不是笼统的愿望。']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let records=JSON.parse(localStorage.getItem('phd-review-records')||'[]'),notes=JSON.parse(localStorage.getItem('phd-quick-notes')||'[]'),draft={},step=0,coords='';
const localDay=(date=new Date())=>{let y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`},day=()=>localDay(),fmt=d=>new Date(d+'T12:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'}),save=()=>{localStorage.setItem('phd-review-records',JSON.stringify(records));window.scheduleCloudSync?.()},saveNotes=()=>{localStorage.setItem('phd-quick-notes',JSON.stringify(notes));window.scheduleCloudSync?.()},esc=s=>(s||'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));
function updateHeaderStat(id){let header=$('header'),settings=$('#settings'),title=$('header h1');if(!header)return;let stat=$('#headerStat');if(!stat){stat=document.createElement('span');stat.id='headerStat';settings?header.insertBefore(stat,settings):header.append(stat)}let diaryWords=typeof diaries==='undefined'?0:diaries.reduce((total,entry)=>total+[...(entry.text||'').replace(/\s/g,'')].length,0);stat.textContent=id==='notesTimeline'?`共 ${notes.length} 条`:id==='diary'?`累计 ${diaryWords.toLocaleString('zh-CN')} 字`:'';stat.hidden=!stat.textContent;if(!stat.hidden&&title){let headerBox=header.getBoundingClientRect(),titleBox=title.getBoundingClientRect();stat.style.left=`${Math.round(titleBox.right-headerBox.left+12)}px`;}}
function page(id){let titles={home:'博士日课',archive:'档案',insights:'洞见',notesTimeline:'随手记',diary:'日记',preferences:'设置',review:'每日复盘'};$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));let title=$('header h1');if(title)title.textContent=titles[id]||'博士日课';updateHeaderStat(id);document.body.classList.toggle('notes-timeline-active',id==='notesTimeline');if(id==='home')home();if(id==='archive')archive();if(id==='insights')insights();if(id==='notesTimeline'){requestAnimationFrame(()=>window.updateNotesTimelineLayout?.());window.renderNotesTimeline?.()}}
function previousTomorrow(){let d=new Date();d.setDate(d.getDate()-1);return records.find(r=>r.date===localDay(d))?.tomorrow?.trim()||''}function home(){let r=records.find(x=>x.date===day()),carried=previousTomorrow(),goals=r?r.goals||'':carried,reviewed=!!r&&Q.every(q=>q[0] in r);$('#heroTitle').textContent=reviewed?'今天的复盘已完成':r?'今日目标已设置':'今天的研究，留下些什么？';$('#heroSub').textContent=reviewed?'随时查看、补充或修改今天的记录。':r?'晚些花 5–10 分钟，完成今天的正式复盘。':'用 5–10 分钟，完成一次有条理的复盘。';$('#heroCta').textContent=reviewed?'查看 / 修改今日复盘　›':'开始今日复盘　›';$('#homeGoals').value=goals;renderNotes();bindCards()}
function noteContent(text){let lines=(text||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);return lines.length?`<ol class="note-lines">${lines.map(line=>`<li>${esc(line)}</li>`).join('')}</ol>`:''}function renderNotes(){let a=notes.filter(n=>n.date===day()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('#todayNotes').innerHTML=a.length?a.map(n=>`<div class="swipe-row note-swipe" data-id="${n.id}"><button class="delete-record delete-note" aria-label="删除随手记">删除</button><div class="note-item"><time>${new Date(n.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time><div class="note-body">${noteContent(n.text)}</div><div class="note-images" data-note-id="${n.id}"></div></div></div>`).join(''):'<p class="empty">今天还没有随手记。</p>';bindNotes();renderNoteImages(a)}async function renderNoteImages(list){for(let note of list){let target=document.querySelector(`.note-images[data-note-id="${note.id}"]`);if(!target)continue;let images=await getNoteImages(note.id);target.innerHTML=images.map(image=>`<img src="${URL.createObjectURL(image.blob)}" alt="随手记图片">`).join('')}}function bindNotes(){$$('.delete-note').forEach(button=>button.onclick=async()=>{let id=button.closest('.note-swipe').dataset.id;if(confirm('删除这条随手记吗？')){await deleteNoteImages([id]);notes=notes.filter(n=>n.id!==id);saveNotes();renderNotes()}});$$('.note-swipe').forEach(row=>{let start=0,delta=0,card=row.querySelector('.note-item');row.addEventListener('pointerdown',event=>{start=event.clientX;delta=0;row.setPointerCapture?.(event.pointerId)});row.addEventListener('pointermove',event=>{if(!start)return;delta=Math.min(0,Math.max(-84,event.clientX-start));if(delta<0)card.style.transform=`translateX(${delta}px)`});row.addEventListener('pointerup',()=>{if(!start)return;card.style.transform='';row.classList.toggle('swiped',delta<-42);start=0});row.addEventListener('pointercancel',()=>{card.style.transform='';start=0})})}function notesForDate(date){return notes.filter(n=>n.date===date).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(n=>`${new Date(n.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} ${n.text}`).join('\n')}function noteTimesForDate(date){let p=n=>String(n).padStart(2,'0');return notes.filter(n=>n.date===date).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(n=>{let d=new Date(n.createdAt);return `${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`}).join('\n')}
function card(r){return `<div class="swipe-row" data-id="${r.id||''}" data-date="${r.date}"><button class="delete-record" aria-label="删除 ${fmt(r.date)} 的记录">删除</button><button class="record" data-id="${r.id||''}" data-date="${r.date}"><p>${fmt(r.date)}</p><strong>${esc((r.goals||'每日复盘').split('\n')[0])}</strong><small>${esc((r.completed||r.goals||'未填写内容').split('\n')[0])}</small></button></div>`}
function bindCards(){
  $$('.record').forEach(button=>button.onclick=event=>{
    let row=button.closest('.swipe-row');
    if(row.classList.contains('swiped')){row.classList.remove('swiped');event.preventDefault();return}
    detail(records.find(record=>record.id===button.dataset.id)||records.find(record=>record.date===button.dataset.date));
  });
  $$('.delete-record:not(.delete-note)').forEach(button=>button.onclick=()=>{
    let row=button.closest('.swipe-row'),id=row.dataset.id,date=row.dataset.date;
    if(confirm('确定删除这篇复盘记录吗？此操作无法撤销。')){records=records.filter(record=>id?record.id!==id:record.date!==date);save();page($('.page.active').id)}
  });
  if(window.phdDesktop){
    $$('.record').forEach(button=>button.oncontextmenu=event=>{
      event.preventDefault();
      let row=button.closest('.swipe-row'),id=row.dataset.id,date=row.dataset.date;
      if(confirm(`删除 ${fmt(date)} 的复盘记录吗？此操作无法撤销。`)){records=records.filter(record=>id?record.id!==id:record.date!==date);save();archive()}
    });
    return;
  }
  $$('.swipe-row:not(.note-swipe):not(.diary-swipe)').forEach(row=>{
    let start=0,delta=0,record=row.querySelector('.record');
    row.addEventListener('pointerdown',event=>{start=event.clientX;delta=0;row.setPointerCapture?.(event.pointerId)});
    row.addEventListener('pointermove',event=>{if(!start)return;delta=Math.min(0,Math.max(-84,event.clientX-start));if(delta<0)record.style.transform=`translateX(${delta}px)`});
    row.addEventListener('pointerup',()=>{if(!start)return;record.style.transform='';row.classList.toggle('swiped',delta<-42);start=0});
    row.addEventListener('pointercancel',()=>{record.style.transform='';start=0});
  });
}
function start(){draft={...(records.find(x=>x.date===day())||{id:crypto.randomUUID(),date:day(),goals:previousTomorrow()})};step=0;coords=draft.location||'';locate();page('review');renderQ()}
function renderQ(){let q=Q[step];$('#stepText').textContent=`问题 ${step+1} / ${Q.length}`;$('#bar').style.width=`${(step+1)/Q.length*100}%`;$('#qTitle').textContent=q[1];$('#qText').textContent=q[2];$('#qHint').textContent=q[3];$('#answer').value=draft[q[0]]||'';$('#back').style.visibility=step?'visible':'hidden';$('#next').textContent=step===Q.length-1?'生成今日记录':'下一题'}function persist(){draft[Q[step][0]]=$('#answer').value.trim()}
function advance(){persist();if(step<Q.length-1){step++;renderQ()}else{draft.location=coords;let i=records.findIndex(x=>x.date===draft.date);i<0?records.push(draft):records[i]=draft;save();maybeWpsBackup();page('home');detail(draft)}}
function locate(){if(!navigator.geolocation){$('#location').textContent='此浏览器不支持定位';return}$('#location').textContent='正在获取记录位置…';navigator.geolocation.getCurrentPosition(p=>{coords=`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;$('#location').textContent=`已记录位置：${coords}`},e=>$('#location').textContent=e.code===1?'未授予位置权限；仍可正常复盘。':'未能定位，可稍后刷新。',{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
function archive(){let term=$('#search').value.toLowerCase(),a=records.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(x=>JSON.stringify(x).toLowerCase().includes(term)),b=notes.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).filter(x=>JSON.stringify(x).toLowerCase().includes(term));$('#records').innerHTML=`<h2 class="archive-heading">复盘记录</h2>${a.length?a.map(card).join(''):'<p class="empty">没有匹配的复盘记录。</p>'}<h2 class="archive-heading">随手记</h2>${b.length?b.map(n=>`<button class="archive-note" data-note-id="${n.id}"><time>${fmt(n.date)}　${new Date(n.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time>${noteContent(n.text)}${n.images?.length?'<small>含图片</small>':''}</button>`).join(''):'<p class="empty">没有匹配的随手记。</p>'}`;bindCards();$$('.archive-note').forEach(button=>button.onclick=()=>noteDetail(notes.find(n=>n.id===button.dataset.noteId)))}
async function noteDetail(note){if(!note)return;let images=await getNoteImages(note.id);$('#detail').innerHTML=`<h2>${fmt(note.date)} · 随手记</h2><div class="detail-item"><h3>${new Date(note.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</h3>${noteContent(note.text)}<div class="note-images">${images.map(image=>`<img src="${URL.createObjectURL(image.blob)}" alt="随手记图片">`).join('')}</div></div>`;$('#modal').classList.remove('hidden')}
function detail(r){if(!r)return;let l=r.location?`<div class="detail-item"><h3>记录位置</h3><a target="_blank" href="https://maps.apple.com/?ll=${encodeURIComponent(r.location)}">${r.location}</a></div>`:'';$('#detail').innerHTML=`<h2>${fmt(r.date)} · 每日复盘</h2>${l}${Q.map(q=>`<div class="detail-item"><h3>${q[1]}</h3>${list(r[q[0]])}</div>`).join('')}`;$('#modal').classList.remove('hidden')}
function list(v){let a=(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return a.length?`<ol>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:'<span>—</span>'}
let chartDays=7;function summaryItems(a,key){return a.slice().sort((x,y)=>y.date.localeCompare(x.date)).flatMap(r=>(r[key]||'').split(/\r?\n/).map(t=>t.trim()).filter(Boolean).map((text,index)=>({date:r.date,key,index,text})))}function summaryGroup(title,items,empty){return `<section class="summary-group"><h3>${title}</h3>${items.length?`<ol>${items.slice(0,10).map(item=>`<li><time>${fmt(item.date)}</time>${esc(item.text)}</li>`).join('')}</ol>`:`<p>${empty}</p>`}</section>`}function insights(){let cutoff=new Date();cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-chartDays+1);let a=records.filter(x=>new Date(x.date+'T12:00')>=cutoff),count=k=>a.filter(x=>x[k]?.trim()).length;$('#stats').innerHTML=`<div><span>记录天数</span><b>${a.length}</b><small>/ ${chartDays} 天</small></div><div><span>解决问题</span><b>${count('solved')}</b><small>天有沉淀</small></div><div><span>待推进</span><b>${count('unsolved')}</b><small>天有记录</small></div>`;let bars=[];for(let i=chartDays-1;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let r=records.find(x=>x.date===localDay(d)),n=r?Q.filter(q=>r[q[0]]?.trim()).length:0;bars.push(`<div><i style="height:${n/Q.length*100}%"></i><span>${d.getMonth()+1}/${d.getDate()}</span></div>`)}$('#chart').innerHTML=bars.join('');$('#summaryTitle').textContent=chartDays===7?'本周复盘':'本月复盘';if(!a.length){$('#summary').innerHTML='<p class="empty">开始每日记录后，这里会自动生成阶段性回顾。</p>';return}let completed=summaryItems(a,'completed'),solved=summaryItems(a,'solved'),unsolved=summaryItems(a,'unsolved'),blockers=summaryItems(a,'blockers'),plans=summaryItems(a,'tomorrow');$('#summary').innerHTML=`<p class="summary-intro">本阶段已记录 ${a.length}/${chartDays} 天；以下内容由你的每日复盘自动汇总。</p>${summaryGroup('本阶段推进',completed,'暂未记录完成的工作。')}${summaryGroup('已打通的问题',solved,'暂未记录已解决问题。')}${summaryGroup('仍待推进',unsolved,'暂未记录未解决问题。')}${summaryGroup('反复出现的卡点',blockers,'暂未记录难点或卡点。')}${summaryGroup(chartDays===7?'下周可延续的行动':'下一步行动',plans,'暂未记录后续计划。')}`}
function exportExcel(){if(!records.length&&!notes.length)return alert('还没有可导出的记录。');if(!window.XLSX)return alert('Excel 组件未加载，请联网后重试。');let dates=[...new Set([...records.map(r=>r.date),...notes.map(n=>n.date)])].sort(),rows=dates.map(date=>{let r=records.find(x=>x.date===date)||{};return Object.fromEntries([['日期',date],['记录位置',r.location||''],['今日核心目标',(r.goals||'').split(/\r?\n/).filter(Boolean).map((x,i)=>`${i+1}. ${x}`).join('\n')],...Q.map(q=>[q[1],(r[q[0]]||'').split(/\r?\n/).filter(Boolean).map((x,i)=>`${i+1}. ${x}`).join('\n')]),['随手记',notesForDate(date)]])}),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:13},{wch:20},{wch:35},...Q.map(()=>({wch:35})),{wch:42}];let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'每日复盘');let d=new Date(),p=n=>String(n).padStart(2,'0'),stamp=`${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;XLSX.writeFile(wb,`博士日课复盘记录_${stamp}.xlsx`)}
function excelBlob(){if(!window.XLSX)throw new Error('Excel 组件未加载，请联网后重试。');let rows=records.map(r=>Object.fromEntries([['日期',r.date],['记录位置',r.location||''],...Q.map(q=>[q[1],(r[q[0]]||'').split(/\r?\n/).filter(Boolean).map((x,i)=>`${i+1}. ${x}`).join('\n')])])),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:13},{wch:20},...Q.map(()=>({wch:35}))];let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'每日复盘');return new Blob([XLSX.write(wb,{bookType:'xlsx',type:'array'})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}function wpsStatus(text){let el=$('#wpsStatus');if(el)el.textContent=text}function dueWps(){let cadence=localStorage.getItem('phd-wps-cadence')||'manual',last=+localStorage.getItem('phd-wps-last')||0,span=cadence==='daily'?86400000:cadence==='weekly'?604800000:Infinity;return Date.now()-last>=span}function loadWps(){let cadence=localStorage.getItem('phd-wps-cadence')||'manual';$('#wpsCadence').value=cadence;let last=+localStorage.getItem('phd-wps-last')||0;wpsStatus(last?`上次备份：${new Date(last).toLocaleString('zh-CN')}`:(cadence==='manual'?'尚未备份':'备份已到期'))}function maybeWpsBackup(){if(dueWps())setTimeout(()=>alert('已到 WPS 备份周期。请到“设置”点击“备份到 WPS”。'),300)}async function backupToWps(){if(!records.length){wpsStatus('还没有可备份的记录。');return}try{let d=new Date(),p=n=>String(n).padStart(2,'0'),file=new File([excelBlob()],`博士日课复盘记录_${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}.xlsx`,{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'博士日课复盘记录',files:[file]});localStorage.setItem('phd-wps-last',String(Date.now()));wpsStatus(`已完成备份：${new Date().toLocaleString('zh-CN')}`)}else{download(file,'博士日课复盘记录.xlsx',file.type);wpsStatus('已下载 Excel，请在“文件”中选择用 WPS 打开。')}}catch(error){if(error.name!=='AbortError')wpsStatus(`生成备份失败：${error.message}`)}}function download(content,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function calendar(){download('BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:phd-review-2300\r\nDTSTART:20260730T230000\r\nDTEND:20260730T231000\r\nRRULE:FREQ=DAILY\r\nSUMMARY:博士日课：每日复盘\r\nDESCRIPTION:花 5–10 分钟记录今天的工作、问题和明日计划。\r\nBEGIN:VALARM\r\nTRIGGER:PT0M\r\nACTION:DISPLAY\r\nDESCRIPTION:每日复盘时间到了\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR','博士日课-每晚23点提醒.ics','text/calendar')}
$('#today').textContent=fmt(day());$('#start').onclick=start;$('#next').onclick=advance;$('#back').onclick=()=>{persist();if(step){step--;renderQ()}};$('#refreshLocation').onclick=locate;$('#settings').onclick=()=>{page('preferences');loadWps()};$$('nav button').forEach(x=>x.onclick=()=>page(x.dataset.page));$('#search').oninput=archive;$$('.segmented button').forEach(x=>x.onclick=()=>{chartDays=+x.dataset.days;$$('.segmented button').forEach(y=>y.classList.toggle('selected',y===x));insights()});$('#excel').onclick=exportExcel;$('#json').onclick=()=>download(JSON.stringify(records,null,2),'博士日课数据备份.json','application/json');$('#locate').onclick=locate;$('#wpsCadence').onchange=e=>{localStorage.setItem('phd-wps-cadence',e.target.value);loadWps()};$('#wpsBackup').onclick=backupToWps;$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};home();if('serviceWorker'in navigator&&!window.phdDesktop)navigator.serviceWorker.register('sw.js');
