let calendarMonth;
const dateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
noteContent=text=>{let lines=(text||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);return lines.map(line=>`<p class="note-paragraph">${esc(line)}</p>`).join('')};
function archiveDates(){return new Set([...records.map(record=>record.date),...notes.map(note=>note.date)])}
function renderArchiveCalendar(){let selected=$('#archiveDate').value||day(),current=calendarMonth||new Date(`${selected}T12:00`),year=current.getFullYear(),month=current.getMonth(),first=new Date(year,month,1).getDay(),total=new Date(year,month+1,0).getDate(),dates=archiveDates(),cells=[];for(let i=0;i<first;i++)cells.push('<button class="blank" disabled></button>');for(let date=1;date<=total;date++){let key=dateKey(new Date(year,month,date));cells.push(`<button class="${key===selected?'selected ':''}${dates.has(key)?'has-entry':''}" data-date="${key}" type="button">${date}</button>`)}$('#archiveCalendar').innerHTML=`<div class="calendar-head"><button id="calendarPrev" type="button" aria-label="上个月">‹</button><b>${year} 年 ${month+1} 月</b><button id="calendarNext" type="button" aria-label="下个月">›</button></div><div class="calendar-week"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class="calendar-grid">${cells.join('')}</div><p class="calendar-legend"><i></i>有复盘或随手记</p>`;$('#calendarPrev').onclick=()=>{calendarMonth=new Date(year,month-1,1);renderArchiveCalendar()};$('#calendarNext').onclick=()=>{calendarMonth=new Date(year,month+1,1);renderArchiveCalendar()};$$('.calendar-grid [data-date]').forEach(button=>button.onclick=()=>{let value=button.dataset.date;$('#archiveDate').value=value;$('#archiveDateButton').textContent=fmt(value);$('#archiveCalendar').classList.add('hidden');calendarMonth=new Date(`${value}T12:00`);archive()})}
archive=function(){let term=$('#search').value.toLowerCase(),selected=$('#archiveDate').value,a=records.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(item=>(!selected||item.date===selected)&&JSON.stringify(item).toLowerCase().includes(term)),b=notes.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).filter(item=>(!selected||item.date===selected)&&JSON.stringify(item).toLowerCase().includes(term)),title=selected?fmt(selected):'全部日期';$('#records').innerHTML=`<h2 class="archive-heading">${title} · 复盘记录</h2>${a.length?a.map(card).join(''):'<p class="empty">这一天没有复盘记录。</p>'}<h2 class="archive-heading">${title} · 随手记</h2>${b.length?b.map(note=>`<button class="archive-note" data-note-id="${note.id}"><time>${fmt(note.date)}　${new Date(note.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time>${noteContent(note.text)}${note.images?.length?'<small>含图片</small>':''}</button>`).join(''):'<p class="empty">这一天没有随手记。</p>'}`;bindCards();$$('.archive-note').forEach(button=>button.onclick=()=>openArchiveNoteEditor(notes.find(note=>note.id===button.dataset.noteId)))};
$('#archiveDate').value=day();
$('#archiveDateButton').textContent=fmt(day());
$('#archiveDateButton').onclick=()=>{let calendar=$('#archiveCalendar');calendar.classList.toggle('hidden');if(!calendar.classList.contains('hidden')){calendarMonth=new Date(`${$('#archiveDate').value}T12:00`);renderArchiveCalendar()}};
$('#search').oninput=archive;
let archiveEditingNote=null;
function openArchiveNoteEditor(note){if(!note)return;archiveEditingNote=note;noteInput.value=note.text||'';pendingNoteImages=[];renderPendingNoteImages();$('.note-editor h2').textContent='编辑随手记';$('.note-editor p').textContent='可修改文字，也可以继续添加图片；原有图片会保留。';$('#saveNote').textContent='保存修改';noteModal.classList.remove('hidden');setTimeout(()=>noteInput.focus(),50)}
$('#saveNote').onclick=async()=>{let text=noteInput.value.trim();if(archiveEditingNote&&!text){await deleteNoteImages([archiveEditingNote.id]);notes=notes.filter(note=>note.id!==archiveEditingNote.id);saveNotes();noteModal.classList.add('hidden');resetArchiveNoteEditor();archive();return}if(!text&&!pendingNoteImages.length)return noteInput.focus();if(!archiveEditingNote){let now=new Date(),id=crypto.randomUUID(),imageIds=await saveNoteImages(id,pendingNoteImages,now);notes.push({id,date:day(),createdAt:now.toISOString(),text,images:imageIds});saveNotes();noteModal.classList.add('hidden');renderNotes();return}let added=await saveNoteImages(archiveEditingNote.id,pendingNoteImages,new Date(archiveEditingNote.createdAt)),index=notes.findIndex(note=>note.id===archiveEditingNote.id);if(index>=0)notes[index]={...notes[index],text,images:[...(notes[index].images||[]),...added]};saveNotes();archiveEditingNote=null;noteModal.classList.add('hidden');$('.note-editor h2').textContent='随手记';$('.note-editor p').textContent='会自动记录当前日期与时间，并在 Excel 中按天汇总。';$('#saveNote').textContent='保存随手记';archive()};
function resetArchiveNoteEditor(){archiveEditingNote=null;$('.note-editor h2').textContent='随手记';$('.note-editor p').textContent='会自动记录当前日期与时间，并在 Excel 中按天汇总。';$('#saveNote').textContent='保存随手记'}
$('#quickNote').addEventListener('click',resetArchiveNoteEditor);
$('#closeNote').addEventListener('click',resetArchiveNoteEditor);
noteModal.addEventListener('click',event=>{if(event.target===noteModal)resetArchiveNoteEditor()});
