archive=function(){let term=$('#search').value.toLowerCase(),selected=$('#archiveDate').value,a=records.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(item=>(!selected||item.date===selected)&&JSON.stringify(item).toLowerCase().includes(term)),b=notes.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).filter(item=>(!selected||item.date===selected)&&JSON.stringify(item).toLowerCase().includes(term)),title=selected?fmt(selected):'全部日期';$('#records').innerHTML=`<h2 class="archive-heading">${title} · 复盘记录</h2>${a.length?a.map(card).join(''):'<p class="empty">这一天没有复盘记录。</p>'}<h2 class="archive-heading">${title} · 随手记</h2>${b.length?b.map(note=>`<button class="archive-note" data-note-id="${note.id}"><time>${fmt(note.date)}　${new Date(note.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time>${noteContent(note.text)}${note.images?.length?'<small>含图片</small>':''}</button>`).join(''):'<p class="empty">这一天没有随手记。</p>'}`;bindCards();$$('.archive-note').forEach(button=>button.onclick=()=>openArchiveNoteEditor(notes.find(note=>note.id===button.dataset.noteId)))};
$('#archiveDate').value=day();
$('#archiveDate').onchange=archive;
$('#search').oninput=archive;
let archiveEditingNote=null;
function openArchiveNoteEditor(note){if(!note)return;archiveEditingNote=note;noteInput.value=note.text||'';pendingNoteImages=[];renderPendingNoteImages();$('.note-editor h2').textContent='编辑随手记';$('.note-editor p').textContent='可修改文字，也可以继续添加图片；原有图片会保留。';$('#saveNote').textContent='保存修改';noteModal.classList.remove('hidden');setTimeout(()=>noteInput.focus(),50)}
$('#saveNote').onclick=async()=>{let text=noteInput.value.trim();if(!text&&!pendingNoteImages.length&&!archiveEditingNote?.images?.length)return noteInput.focus();if(!archiveEditingNote){let now=new Date(),id=crypto.randomUUID(),imageIds=await saveNoteImages(id,pendingNoteImages,now);notes.push({id,date:day(),createdAt:now.toISOString(),text,images:imageIds});saveNotes();noteModal.classList.add('hidden');renderNotes();return}let added=await saveNoteImages(archiveEditingNote.id,pendingNoteImages,new Date(archiveEditingNote.createdAt)),index=notes.findIndex(note=>note.id===archiveEditingNote.id);if(index>=0)notes[index]={...notes[index],text,images:[...(notes[index].images||[]),...added]};saveNotes();archiveEditingNote=null;noteModal.classList.add('hidden');$('.note-editor h2').textContent='随手记';$('.note-editor p').textContent='会自动记录当前日期与时间，并在 Excel 中按天汇总。';$('#saveNote').textContent='保存随手记';archive()};
function resetArchiveNoteEditor(){archiveEditingNote=null;$('.note-editor h2').textContent='随手记';$('.note-editor p').textContent='会自动记录当前日期与时间，并在 Excel 中按天汇总。';$('#saveNote').textContent='保存随手记'}
$('#quickNote').addEventListener('click',resetArchiveNoteEditor);
$('#closeNote').addEventListener('click',resetArchiveNoteEditor);
noteModal.addEventListener('click',event=>{if(event.target===noteModal)resetArchiveNoteEditor()});
