function allExportRows(){let dates=[...new Set([...records.map(r=>r.date),...notes.map(n=>n.date),...diaries.map(d=>d.date)])].sort();return dates.map(date=>{let r=records.find(x=>x.date===date)||{},diary=diaries.find(x=>x.date===date)||{};return Object.fromEntries([['日期',date],['记录地点',r.location||''],['今日核心目标',numbered(r.goals)],...Q.map(q=>[q[1],numbered(r[q[0]])]),['随手记',notesForDate(date)],['随手记记录时间',noteTimesForDate(date)],['日记',diary.text||''],['日记地点',diary.place||''],['日记图片数',(diary.images||[]).length||'']])})}
const numbered=value=>(value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((x,index)=>`${index+1}. ${x}`).join('\n');
const exportFont={name:'Microsoft YaHei',sz:10,color:{rgb:'1F2937'}},thin={style:'thin',color:{rgb:'D9E2F0'}};
function styleExportSheet(ws,rows){let range=XLSX.utils.decode_range(ws['!ref']),last=range.e.r+1,lastCol=XLSX.utils.encode_col(range.e.c);ws['!cols']=[{wch:13},{wch:24},{wch:34},...Q.map(()=>({wch:34})),{wch:42},{wch:20},{wch:50},{wch:28}];ws['!rows']=[{hpt:30},...rows.map(row=>{let height=Math.min(150,Math.max(36,...Object.values(row).map(value=>String(value||'').split('\n').length*18+12)));return {hpt:height}})];for(let col=0;col<=range.e.c;col++){let cell=ws[XLSX.utils.encode_cell({r:0,c:col})];cell.s={font:{name:'Microsoft YaHei',sz:11,bold:true,color:{rgb:'FFFFFF'}},fill:{fgColor:{rgb:'1769AA'}},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:thin,bottom:thin,left:thin,right:thin}}}for(let row=1;row<=range.e.r;row++)for(let col=0;col<=range.e.c;col++){let cell=ws[XLSX.utils.encode_cell({r:row,c:col})];if(!cell)continue;cell.s={font:exportFont,fill:row%2?{fgColor:{rgb:'F6F9FC'}}:undefined,alignment:{vertical:'top',horizontal:col<2?'center':'left',wrapText:true},border:{bottom:thin}}}ws['!autofilter']={ref:`A1:${lastCol}${last}`};ws['!freeze']={xSplit:0,ySplit:1};ws['!margins']={left:.25,right:.25,top:.5,bottom:.5,header:.2,footer:.2};ws['!pageSetup']={orientation:'landscape',paperSize:9,fitToWidth:1,fitToHeight:0};ws['!printArea']=`A1:${lastCol}${last}`}
function printSheet(rows){let data=[['博士日课 · 打印版'],['导出时间',new Date().toLocaleString('zh-CN')]],merges=[XLSX.utils.decode_range('A1:F1')];for(let entry of rows){data.push([],[`日期：${entry['日期']}`]);merges.push(XLSX.utils.decode_range(`A${data.length}:F${data.length}`));for(let [label,value] of Object.entries(entry)){if(label==='日期'||!value)continue;data.push([label,value]);merges.push(XLSX.utils.decode_range(`B${data.length}:F${data.length}`))}}let ws=XLSX.utils.aoa_to_sheet(data);ws['!merges']=merges;ws['!cols']=[{wch:16},{wch:25},{wch:25},{wch:25},{wch:25},{wch:25}];ws['!rows']=data.map((row,index)=>({hpt:index===0?30:index===1?22:Math.min(130,Math.max(24,String(row[1]||row[0]||'').split('\n').length*18+12))}));for(let row=0;row<data.length;row++){for(let col=0;col<6;col++){let cell=ws[XLSX.utils.encode_cell({r:row,c:col})];if(!cell)continue;let isTitle=row===0,isDate=data[row].length===1&&row>1,isLabel=col===0&&row>1;cell.s={font:{name:'Microsoft YaHei',sz:isTitle?16:isDate?12:10,bold:isTitle||isDate||isLabel,color:{rgb:isTitle?'FFFFFF':'1F2937'}},fill:isTitle?{fgColor:{rgb:'1769AA'}}:isDate?{fgColor:{rgb:'DCEEFF'}}:isLabel?{fgColor:{rgb:'EEF4FA'}}:undefined,alignment:{vertical:'top',horizontal:isTitle||isDate?'center':'left',wrapText:true},border:{bottom:thin}}}}ws['!margins']={left:.45,right:.45,top:.55,bottom:.55,header:.2,footer:.25};ws['!pageSetup']={orientation:'portrait',paperSize:9,fitToWidth:1,fitToHeight:0};return ws}
function buildExportBook(){let rows=allExportRows(),wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);styleExportSheet(ws,rows);XLSX.utils.book_append_sheet(wb,ws,'每日复盘');XLSX.utils.book_append_sheet(wb,printSheet(rows),'打印版');return wb}
function exportExcel(){if(!records.length&&!notes.length&&!diaries.length)return alert('还没有可导出的记录。');if(!window.__styledXlsxReady)return alert('正在加载 Excel 排版组件，请稍后再试。');let wb=buildExportBook(),d=new Date(),p=n=>String(n).padStart(2,'0'),stamp=`${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;XLSX.writeFile(wb,`博士日课复盘记录_${stamp}.xlsx`,{cellStyles:true})}
function excelBlob(){if(!window.__styledXlsxReady)throw new Error('Excel 排版组件未加载，请联网后重试。');return new Blob([XLSX.write(buildExportBook(),{bookType:'xlsx',type:'array',cellStyles:true})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
$('#excel').onclick=exportExcel;
