const imageDb=()=>new Promise((resolve,reject)=>{let request=indexedDB.open('phd-daily-images',1);request.onupgradeneeded=()=>request.result.createObjectStore('images',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const imageRequest=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const imageExtension=file=>file.name?.split('.').pop()?.toLowerCase()||file.type?.split('/').pop()?.replace('jpeg','jpg')||'jpg';
const imageStamp=date=>{let d=new Date(date),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`};
async function saveNoteImages(noteId,files,createdAt=new Date()){let db=await imageDb(),ids=[],stamp=imageStamp(createdAt);for(let [index,file] of [...files].entries()){let id=crypto.randomUUID(),suffix=files.length>1?`_${index+1}`:'',name=`随手记${stamp}${suffix}.${imageExtension(file)}`;await imageRequest(db.transaction('images','readwrite').objectStore('images').put({id,noteId,name,type:file.type||'image/jpeg',blob:file}));ids.push(id)}return ids}
async function getNoteImages(noteId){let db=await imageDb(),all=await imageRequest(db.transaction('images').objectStore('images').getAll());return all.filter(image=>image.noteId===noteId)}
async function allNoteImages(){let db=await imageDb();return imageRequest(db.transaction('images').objectStore('images').getAll())}
async function deleteNoteImages(noteIds){if(!noteIds?.length)return;let db=await imageDb(),all=await imageRequest(db.transaction('images').objectStore('images').getAll());for(let image of all.filter(image=>noteIds.includes(image.noteId)))await imageRequest(db.transaction('images','readwrite').objectStore('images').delete(image.id))}
async function clearNoteImages(){let db=await imageDb();await imageRequest(db.transaction('images','readwrite').objectStore('images').clear())}
async function restoreNoteImages(images){let db=await imageDb();for(let image of images)await imageRequest(db.transaction('images','readwrite').objectStore('images').put(image))}
